version: '3'

services:
  app:
    build: docker
    container_name: "hexo-docker-demo"
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ./docker/apache.conf:/etc/apache2/sites-available/000-default.conf
      - .:/var/www/
  db:
    image: "mysql:latest"
    restart: always
    volumes:
        - db-data:/var/lib/mysql/
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: mydb
        MYSQL_USER: amira
        MYSQL_PASSWORD: amiraj
    ports:
      - "3308:3308"

volumes:
  db-data:
